[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "all"

[licenses]
allow = ["MIT"]

[licenses.private]
ignore = false

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
